name: Deploy to prod
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying the frontend to prod    
    steps:
      - name: Deploy via SSH Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.63.175.166
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # The script below runs directly on your server
          script: |
            # 1. Load NVM so Node/pnpm work
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Navigate and Pull code
            cd ~/projects/bms
            git pull origin main
            
            # 3. Install and Build
            pnpm install
            pnpm build
            
            # 4. Restart the server
            pm2 restart all